name: 'Publish to hex'
description: 'Publish a hex package from a mix.exs'
inputs:
  hex-api-key: 
    description: "Authentication token to use when publishing to hex"
    required: true
  working-directory:
    description: "Path within the repo to the folder where the mix.exs file lives"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: install dependencies
      run: mix deps get
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: publish package
      run: |
        mix hex.publish --yes
      env:
        HEX_API_KEY: ${{ inputs.hex-api-key }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
